//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Atlantis.Framework.NebulaUserAdd.Impl.StorageWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GoDaddy_Storage_Service_User_Management_v_0_1Binding", Namespace="urn:urn:gd-storage-service-um")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Bandwidth))]
    public partial class GoDaddy_Storage_Service_User_Management_v_0_1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UserAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserDisableOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserEnableOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserModifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserRemoveOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserRestoreOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GoDaddy_Storage_Service_User_Management_v_0_1() {
            this.Url = global::Atlantis.Framework.NebulaUserAdd.Impl.Properties.Settings.Default.Atlantis_Framework_NebulaUserAdd_Impl_StorageWS_GoDaddy_Storage_Service_User_Management_v_0_1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UserAddCompletedEventHandler UserAddCompleted;
        
        /// <remarks/>
        public event UserDisableCompletedEventHandler UserDisableCompleted;
        
        /// <remarks/>
        public event UserEnableCompletedEventHandler UserEnableCompleted;
        
        /// <remarks/>
        public event UserInfoCompletedEventHandler UserInfoCompleted;
        
        /// <remarks/>
        public event UserKeyCompletedEventHandler UserKeyCompleted;
        
        /// <remarks/>
        public event UserModifyCompletedEventHandler UserModifyCompleted;
        
        /// <remarks/>
        public event UserRemoveCompletedEventHandler UserRemoveCompleted;
        
        /// <remarks/>
        public event UserRestoreCompletedEventHandler UserRestoreCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gd-storage-service-um#UserAdd", RequestNamespace="urn:gd-storage-service-um", ResponseNamespace="urn:gd-storage-service-um")]
        [return: System.Xml.Serialization.SoapElementAttribute("UserAddResponse")]
        public UserAddResponse UserAdd([System.Xml.Serialization.SoapElementAttribute("UserAdd")] UserAdd UserAdd1) {
            object[] results = this.Invoke("UserAdd", new object[] {
                        UserAdd1});
            return ((UserAddResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UserAddAsync(UserAdd UserAdd1) {
            this.UserAddAsync(UserAdd1, null);
        }
        
        /// <remarks/>
        public void UserAddAsync(UserAdd UserAdd1, object userState) {
            if ((this.UserAddOperationCompleted == null)) {
                this.UserAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAddOperationCompleted);
            }
            this.InvokeAsync("UserAdd", new object[] {
                        UserAdd1}, this.UserAddOperationCompleted, userState);
        }
        
        private void OnUserAddOperationCompleted(object arg) {
            if ((this.UserAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAddCompleted(this, new UserAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gd-storage-service-um#UserDisable", RequestNamespace="urn:gd-storage-service-um", ResponseNamespace="urn:gd-storage-service-um")]
        [return: System.Xml.Serialization.SoapElementAttribute("UserDisableResponse")]
        public UserDisableResponse UserDisable([System.Xml.Serialization.SoapElementAttribute("UserDisable")] UserDisable UserDisable1) {
            object[] results = this.Invoke("UserDisable", new object[] {
                        UserDisable1});
            return ((UserDisableResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UserDisableAsync(UserDisable UserDisable1) {
            this.UserDisableAsync(UserDisable1, null);
        }
        
        /// <remarks/>
        public void UserDisableAsync(UserDisable UserDisable1, object userState) {
            if ((this.UserDisableOperationCompleted == null)) {
                this.UserDisableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserDisableOperationCompleted);
            }
            this.InvokeAsync("UserDisable", new object[] {
                        UserDisable1}, this.UserDisableOperationCompleted, userState);
        }
        
        private void OnUserDisableOperationCompleted(object arg) {
            if ((this.UserDisableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserDisableCompleted(this, new UserDisableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gd-storage-service-um#UserEnable", RequestNamespace="urn:gd-storage-service-um", ResponseNamespace="urn:gd-storage-service-um")]
        [return: System.Xml.Serialization.SoapElementAttribute("UserEnableResponse")]
        public UserEnableResponse UserEnable([System.Xml.Serialization.SoapElementAttribute("UserEnable")] UserEnable UserEnable1) {
            object[] results = this.Invoke("UserEnable", new object[] {
                        UserEnable1});
            return ((UserEnableResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UserEnableAsync(UserEnable UserEnable1) {
            this.UserEnableAsync(UserEnable1, null);
        }
        
        /// <remarks/>
        public void UserEnableAsync(UserEnable UserEnable1, object userState) {
            if ((this.UserEnableOperationCompleted == null)) {
                this.UserEnableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserEnableOperationCompleted);
            }
            this.InvokeAsync("UserEnable", new object[] {
                        UserEnable1}, this.UserEnableOperationCompleted, userState);
        }
        
        private void OnUserEnableOperationCompleted(object arg) {
            if ((this.UserEnableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserEnableCompleted(this, new UserEnableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gd-storage-service-um#UserInfo", RequestNamespace="urn:gd-storage-service-um", ResponseNamespace="urn:gd-storage-service-um")]
        [return: System.Xml.Serialization.SoapElementAttribute("UserInfoResponse")]
        public UserInfoResponse UserInfo([System.Xml.Serialization.SoapElementAttribute("UserInfo")] UserInfo UserInfo1) {
            object[] results = this.Invoke("UserInfo", new object[] {
                        UserInfo1});
            return ((UserInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UserInfoAsync(UserInfo UserInfo1) {
            this.UserInfoAsync(UserInfo1, null);
        }
        
        /// <remarks/>
        public void UserInfoAsync(UserInfo UserInfo1, object userState) {
            if ((this.UserInfoOperationCompleted == null)) {
                this.UserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserInfoOperationCompleted);
            }
            this.InvokeAsync("UserInfo", new object[] {
                        UserInfo1}, this.UserInfoOperationCompleted, userState);
        }
        
        private void OnUserInfoOperationCompleted(object arg) {
            if ((this.UserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserInfoCompleted(this, new UserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gd-storage-service-um#UserKey", RequestNamespace="urn:gd-storage-service-um", ResponseNamespace="urn:gd-storage-service-um")]
        [return: System.Xml.Serialization.SoapElementAttribute("UserKeyResponse")]
        public UserKeyResponse UserKey([System.Xml.Serialization.SoapElementAttribute("UserKey")] UserKey UserKey1) {
            object[] results = this.Invoke("UserKey", new object[] {
                        UserKey1});
            return ((UserKeyResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UserKeyAsync(UserKey UserKey1) {
            this.UserKeyAsync(UserKey1, null);
        }
        
        /// <remarks/>
        public void UserKeyAsync(UserKey UserKey1, object userState) {
            if ((this.UserKeyOperationCompleted == null)) {
                this.UserKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserKeyOperationCompleted);
            }
            this.InvokeAsync("UserKey", new object[] {
                        UserKey1}, this.UserKeyOperationCompleted, userState);
        }
        
        private void OnUserKeyOperationCompleted(object arg) {
            if ((this.UserKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserKeyCompleted(this, new UserKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gd-storage-service-um#UserModify", RequestNamespace="urn:gd-storage-service-um", ResponseNamespace="urn:gd-storage-service-um")]
        [return: System.Xml.Serialization.SoapElementAttribute("UserModifyResponse")]
        public UserModifyResponse UserModify([System.Xml.Serialization.SoapElementAttribute("UserModify")] UserModify UserModify1) {
            object[] results = this.Invoke("UserModify", new object[] {
                        UserModify1});
            return ((UserModifyResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UserModifyAsync(UserModify UserModify1) {
            this.UserModifyAsync(UserModify1, null);
        }
        
        /// <remarks/>
        public void UserModifyAsync(UserModify UserModify1, object userState) {
            if ((this.UserModifyOperationCompleted == null)) {
                this.UserModifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserModifyOperationCompleted);
            }
            this.InvokeAsync("UserModify", new object[] {
                        UserModify1}, this.UserModifyOperationCompleted, userState);
        }
        
        private void OnUserModifyOperationCompleted(object arg) {
            if ((this.UserModifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserModifyCompleted(this, new UserModifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gd-storage-service-um#UserRemove", RequestNamespace="urn:gd-storage-service-um", ResponseNamespace="urn:gd-storage-service-um")]
        [return: System.Xml.Serialization.SoapElementAttribute("UserRemoveResponse")]
        public UserRemoveResponse UserRemove([System.Xml.Serialization.SoapElementAttribute("UserRemove")] UserRemove UserRemove1) {
            object[] results = this.Invoke("UserRemove", new object[] {
                        UserRemove1});
            return ((UserRemoveResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UserRemoveAsync(UserRemove UserRemove1) {
            this.UserRemoveAsync(UserRemove1, null);
        }
        
        /// <remarks/>
        public void UserRemoveAsync(UserRemove UserRemove1, object userState) {
            if ((this.UserRemoveOperationCompleted == null)) {
                this.UserRemoveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserRemoveOperationCompleted);
            }
            this.InvokeAsync("UserRemove", new object[] {
                        UserRemove1}, this.UserRemoveOperationCompleted, userState);
        }
        
        private void OnUserRemoveOperationCompleted(object arg) {
            if ((this.UserRemoveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserRemoveCompleted(this, new UserRemoveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:gd-storage-service-um#UserRestore", RequestNamespace="urn:gd-storage-service-um", ResponseNamespace="urn:gd-storage-service-um")]
        [return: System.Xml.Serialization.SoapElementAttribute("UserRestoreResponse")]
        public UserRestoreResponse UserRestore([System.Xml.Serialization.SoapElementAttribute("UserRestore")] UserRestore UserRestore1) {
            object[] results = this.Invoke("UserRestore", new object[] {
                        UserRestore1});
            return ((UserRestoreResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UserRestoreAsync(UserRestore UserRestore1) {
            this.UserRestoreAsync(UserRestore1, null);
        }
        
        /// <remarks/>
        public void UserRestoreAsync(UserRestore UserRestore1, object userState) {
            if ((this.UserRestoreOperationCompleted == null)) {
                this.UserRestoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserRestoreOperationCompleted);
            }
            this.InvokeAsync("UserRestore", new object[] {
                        UserRestore1}, this.UserRestoreOperationCompleted, userState);
        }
        
        private void OnUserRestoreOperationCompleted(object arg) {
            if ((this.UserRestoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserRestoreCompleted(this, new UserRestoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserAdd {
        
        private string serviceManagerAccessKeyIdField;
        
        private string serviceManagerSignatureField;
        
        private string userUniqueIdField;
        
        private int quotaField;
        
        /// <remarks/>
        public string ServiceManagerAccessKeyId {
            get {
                return this.serviceManagerAccessKeyIdField;
            }
            set {
                this.serviceManagerAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceManagerSignature {
            get {
                return this.serviceManagerSignatureField;
            }
            set {
                this.serviceManagerSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string UserUniqueId {
            get {
                return this.userUniqueIdField;
            }
            set {
                this.userUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public int Quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserRestoreResponse {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserRestore {
        
        private string serviceManagerAccessKeyIdField;
        
        private string serviceManagerSignatureField;
        
        private string userAccessKeyIdField;
        
        /// <remarks/>
        public string ServiceManagerAccessKeyId {
            get {
                return this.serviceManagerAccessKeyIdField;
            }
            set {
                this.serviceManagerAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceManagerSignature {
            get {
                return this.serviceManagerSignatureField;
            }
            set {
                this.serviceManagerSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string UserAccessKeyId {
            get {
                return this.userAccessKeyIdField;
            }
            set {
                this.userAccessKeyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserRemoveResponse {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserRemove {
        
        private string serviceManagerAccessKeyIdField;
        
        private string serviceManagerSignatureField;
        
        private string userAccessKeyIdField;
        
        /// <remarks/>
        public string ServiceManagerAccessKeyId {
            get {
                return this.serviceManagerAccessKeyIdField;
            }
            set {
                this.serviceManagerAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceManagerSignature {
            get {
                return this.serviceManagerSignatureField;
            }
            set {
                this.serviceManagerSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string UserAccessKeyId {
            get {
                return this.userAccessKeyIdField;
            }
            set {
                this.userAccessKeyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserModifyResponse {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserModify {
        
        private string serviceManagerAccessKeyIdField;
        
        private string serviceManagerSignatureField;
        
        private string userAccessKeyIdField;
        
        private int quotaField;
        
        /// <remarks/>
        public string ServiceManagerAccessKeyId {
            get {
                return this.serviceManagerAccessKeyIdField;
            }
            set {
                this.serviceManagerAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceManagerSignature {
            get {
                return this.serviceManagerSignatureField;
            }
            set {
                this.serviceManagerSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string UserAccessKeyId {
            get {
                return this.userAccessKeyIdField;
            }
            set {
                this.userAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public int Quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserKeyResponse {
        
        private int codeField;
        
        private string descriptionField;
        
        private string secretKeyField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string SecretKey {
            get {
                return this.secretKeyField;
            }
            set {
                this.secretKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserKey {
        
        private string serviceManagerAccessKeyIdField;
        
        private string serviceManagerSignatureField;
        
        private string userAccessKeyIdField;
        
        private string newKeyField;
        
        /// <remarks/>
        public string ServiceManagerAccessKeyId {
            get {
                return this.serviceManagerAccessKeyIdField;
            }
            set {
                this.serviceManagerAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceManagerSignature {
            get {
                return this.serviceManagerSignatureField;
            }
            set {
                this.serviceManagerSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string UserAccessKeyId {
            get {
                return this.userAccessKeyIdField;
            }
            set {
                this.userAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public string NewKey {
            get {
                return this.newKeyField;
            }
            set {
                this.newKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class Bandwidth {
        
        private System.DateTime dateField;
        
        private int bytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public int Bytes {
            get {
                return this.bytesField;
            }
            set {
                this.bytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserInfoDisk {
        
        private int quotaField;
        
        private int usedField;
        
        /// <remarks/>
        public int Quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
            }
        }
        
        /// <remarks/>
        public int Used {
            get {
                return this.usedField;
            }
            set {
                this.usedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserInfoResponse {
        
        private int codeField;
        
        private string descriptionField;
        
        private string userAccessKeyIdField;
        
        private string secretKeyField;
        
        private string statusField;
        
        private System.DateTime createdDateField;
        
        private UserInfoDisk diskField;
        
        private Bandwidth[] bandwidthResultsField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string UserAccessKeyId {
            get {
                return this.userAccessKeyIdField;
            }
            set {
                this.userAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public string SecretKey {
            get {
                return this.secretKeyField;
            }
            set {
                this.secretKeyField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public UserInfoDisk Disk {
            get {
                return this.diskField;
            }
            set {
                this.diskField = value;
            }
        }
        
        /// <remarks/>
        public Bandwidth[] BandwidthResults {
            get {
                return this.bandwidthResultsField;
            }
            set {
                this.bandwidthResultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserInfo {
        
        private string serviceManagerAccessKeyIdField;
        
        private string serviceManagerSignatureField;
        
        private string userUniqueIdField;
        
        private string userAccessKeyIdField;
        
        private System.DateTime bandwidthStartDateField;
        
        private System.DateTime bandwidthEndDateField;
        
        /// <remarks/>
        public string ServiceManagerAccessKeyId {
            get {
                return this.serviceManagerAccessKeyIdField;
            }
            set {
                this.serviceManagerAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceManagerSignature {
            get {
                return this.serviceManagerSignatureField;
            }
            set {
                this.serviceManagerSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string UserUniqueId {
            get {
                return this.userUniqueIdField;
            }
            set {
                this.userUniqueIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserAccessKeyId {
            get {
                return this.userAccessKeyIdField;
            }
            set {
                this.userAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime BandwidthStartDate {
            get {
                return this.bandwidthStartDateField;
            }
            set {
                this.bandwidthStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime BandwidthEndDate {
            get {
                return this.bandwidthEndDateField;
            }
            set {
                this.bandwidthEndDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserEnableResponse {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserEnable {
        
        private string serviceManagerAccessKeyIdField;
        
        private string serviceManagerSignatureField;
        
        private string userAccessKeyIdField;
        
        /// <remarks/>
        public string ServiceManagerAccessKeyId {
            get {
                return this.serviceManagerAccessKeyIdField;
            }
            set {
                this.serviceManagerAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceManagerSignature {
            get {
                return this.serviceManagerSignatureField;
            }
            set {
                this.serviceManagerSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string UserAccessKeyId {
            get {
                return this.userAccessKeyIdField;
            }
            set {
                this.userAccessKeyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserDisableResponse {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserDisable {
        
        private string serviceManagerAccessKeyIdField;
        
        private string serviceManagerSignatureField;
        
        private string userAccessKeyIdField;
        
        /// <remarks/>
        public string ServiceManagerAccessKeyId {
            get {
                return this.serviceManagerAccessKeyIdField;
            }
            set {
                this.serviceManagerAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceManagerSignature {
            get {
                return this.serviceManagerSignatureField;
            }
            set {
                this.serviceManagerSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string UserAccessKeyId {
            get {
                return this.userAccessKeyIdField;
            }
            set {
                this.userAccessKeyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:urn:gd-storage-service-um")]
    public partial class UserAddResponse {
        
        private int codeField;
        
        private string descriptionField;
        
        private string userAccessKeyIdField;
        
        private string secretKeyField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string UserAccessKeyId {
            get {
                return this.userAccessKeyIdField;
            }
            set {
                this.userAccessKeyIdField = value;
            }
        }
        
        /// <remarks/>
        public string SecretKey {
            get {
                return this.secretKeyField;
            }
            set {
                this.secretKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UserAddCompletedEventHandler(object sender, UserAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAddResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAddResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UserDisableCompletedEventHandler(object sender, UserDisableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserDisableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserDisableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserDisableResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserDisableResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UserEnableCompletedEventHandler(object sender, UserEnableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserEnableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserEnableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserEnableResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserEnableResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UserInfoCompletedEventHandler(object sender, UserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserInfoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UserKeyCompletedEventHandler(object sender, UserKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserKeyResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserKeyResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UserModifyCompletedEventHandler(object sender, UserModifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserModifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserModifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserModifyResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserModifyResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UserRemoveCompletedEventHandler(object sender, UserRemoveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserRemoveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserRemoveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserRemoveResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserRemoveResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UserRestoreCompletedEventHandler(object sender, UserRestoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserRestoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserRestoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserRestoreResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserRestoreResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591