//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Atlantis.Framework.SAGetDomainListByShopper.Impl.SAMobileWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SAMobileWebBinding", Namespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(mwErrorCodeList))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(mwTrafficSourcesStruct))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(mwMostPopDayStruct))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(mwUSVisitorStruct))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(mwVisitorStruct))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(mwDomainStruct))]
    public partial class SAMobileWeb : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDomainListByShopperOperationCompleted;
        
        private System.Threading.SendOrPostCallback VisitorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback USVisByLocationOperationCompleted;
        
        private System.Threading.SendOrPostCallback MostPopularDayOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrafficSourcesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompleteErrorCodeListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SAMobileWeb() {
            this.Url = global::Atlantis.Framework.SAGetDomainListByShopper.Impl.Properties.Settings.Default.Atlantis_Framework_SAGetDomainListByShopper_Impl_SAMobileWeb_SAMobileWeb;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDomainListByShopperCompletedEventHandler GetDomainListByShopperCompleted;
        
        /// <remarks/>
        public event VisitorsCompletedEventHandler VisitorsCompleted;
        
        /// <remarks/>
        public event USVisByLocationCompletedEventHandler USVisByLocationCompleted;
        
        /// <remarks/>
        public event MostPopularDayCompletedEventHandler MostPopularDayCompleted;
        
        /// <remarks/>
        public event TrafficSourcesCompletedEventHandler TrafficSourcesCompleted;
        
        /// <remarks/>
        public event GetCompleteErrorCodeListCompletedEventHandler GetCompleteErrorCodeListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://teststatsweb01.test.glbt1.gdg/admin/mw/SAMobileWebService.php/GetDomainLis" +
            "tByShopper", RequestNamespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb", ResponseNamespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public mwDomainReturnStruct GetDomainListByShopper(string clientid, string shopper) {
            object[] results = this.Invoke("GetDomainListByShopper", new object[] {
                        clientid,
                        shopper});
            return ((mwDomainReturnStruct)(results[0]));
        }
        
        /// <remarks/>
        public void GetDomainListByShopperAsync(string clientid, string shopper) {
            this.GetDomainListByShopperAsync(clientid, shopper, null);
        }
        
        /// <remarks/>
        public void GetDomainListByShopperAsync(string clientid, string shopper, object userState) {
            if ((this.GetDomainListByShopperOperationCompleted == null)) {
                this.GetDomainListByShopperOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDomainListByShopperOperationCompleted);
            }
            this.InvokeAsync("GetDomainListByShopper", new object[] {
                        clientid,
                        shopper}, this.GetDomainListByShopperOperationCompleted, userState);
        }
        
        private void OnGetDomainListByShopperOperationCompleted(object arg) {
            if ((this.GetDomainListByShopperCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDomainListByShopperCompleted(this, new GetDomainListByShopperCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://teststatsweb01.test.glbt1.gdg/admin/mw/SAMobileWebService.php/Visitors", RequestNamespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb", ResponseNamespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public mwVisReturnStruct Visitors(string clientid, string domain, string startDate, string endDate) {
            object[] results = this.Invoke("Visitors", new object[] {
                        clientid,
                        domain,
                        startDate,
                        endDate});
            return ((mwVisReturnStruct)(results[0]));
        }
        
        /// <remarks/>
        public void VisitorsAsync(string clientid, string domain, string startDate, string endDate) {
            this.VisitorsAsync(clientid, domain, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void VisitorsAsync(string clientid, string domain, string startDate, string endDate, object userState) {
            if ((this.VisitorsOperationCompleted == null)) {
                this.VisitorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVisitorsOperationCompleted);
            }
            this.InvokeAsync("Visitors", new object[] {
                        clientid,
                        domain,
                        startDate,
                        endDate}, this.VisitorsOperationCompleted, userState);
        }
        
        private void OnVisitorsOperationCompleted(object arg) {
            if ((this.VisitorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VisitorsCompleted(this, new VisitorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://teststatsweb01.test.glbt1.gdg/admin/mw/SAMobileWebService.php/USVisByLocat" +
            "ion", RequestNamespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb", ResponseNamespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public mwUSVisReturnStruct USVisByLocation(string clientid, string domain, string startDate, string endDate) {
            object[] results = this.Invoke("USVisByLocation", new object[] {
                        clientid,
                        domain,
                        startDate,
                        endDate});
            return ((mwUSVisReturnStruct)(results[0]));
        }
        
        /// <remarks/>
        public void USVisByLocationAsync(string clientid, string domain, string startDate, string endDate) {
            this.USVisByLocationAsync(clientid, domain, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void USVisByLocationAsync(string clientid, string domain, string startDate, string endDate, object userState) {
            if ((this.USVisByLocationOperationCompleted == null)) {
                this.USVisByLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUSVisByLocationOperationCompleted);
            }
            this.InvokeAsync("USVisByLocation", new object[] {
                        clientid,
                        domain,
                        startDate,
                        endDate}, this.USVisByLocationOperationCompleted, userState);
        }
        
        private void OnUSVisByLocationOperationCompleted(object arg) {
            if ((this.USVisByLocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.USVisByLocationCompleted(this, new USVisByLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://teststatsweb01.test.glbt1.gdg/admin/mw/SAMobileWebService.php/MostPopularD" +
            "ay", RequestNamespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb", ResponseNamespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public mwMostPopDayReturnStruct MostPopularDay(string clientid, string domain, string startDate, string endDate) {
            object[] results = this.Invoke("MostPopularDay", new object[] {
                        clientid,
                        domain,
                        startDate,
                        endDate});
            return ((mwMostPopDayReturnStruct)(results[0]));
        }
        
        /// <remarks/>
        public void MostPopularDayAsync(string clientid, string domain, string startDate, string endDate) {
            this.MostPopularDayAsync(clientid, domain, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void MostPopularDayAsync(string clientid, string domain, string startDate, string endDate, object userState) {
            if ((this.MostPopularDayOperationCompleted == null)) {
                this.MostPopularDayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostPopularDayOperationCompleted);
            }
            this.InvokeAsync("MostPopularDay", new object[] {
                        clientid,
                        domain,
                        startDate,
                        endDate}, this.MostPopularDayOperationCompleted, userState);
        }
        
        private void OnMostPopularDayOperationCompleted(object arg) {
            if ((this.MostPopularDayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostPopularDayCompleted(this, new MostPopularDayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://teststatsweb01.test.glbt1.gdg/admin/mw/SAMobileWebService.php/TrafficSourc" +
            "es", RequestNamespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb", ResponseNamespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public mwTrafficSourcesReturnStruct TrafficSources(string clientid, string domain, string startDate, string endDate) {
            object[] results = this.Invoke("TrafficSources", new object[] {
                        clientid,
                        domain,
                        startDate,
                        endDate});
            return ((mwTrafficSourcesReturnStruct)(results[0]));
        }
        
        /// <remarks/>
        public void TrafficSourcesAsync(string clientid, string domain, string startDate, string endDate) {
            this.TrafficSourcesAsync(clientid, domain, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void TrafficSourcesAsync(string clientid, string domain, string startDate, string endDate, object userState) {
            if ((this.TrafficSourcesOperationCompleted == null)) {
                this.TrafficSourcesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrafficSourcesOperationCompleted);
            }
            this.InvokeAsync("TrafficSources", new object[] {
                        clientid,
                        domain,
                        startDate,
                        endDate}, this.TrafficSourcesOperationCompleted, userState);
        }
        
        private void OnTrafficSourcesOperationCompleted(object arg) {
            if ((this.TrafficSourcesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrafficSourcesCompleted(this, new TrafficSourcesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://teststatsweb01.test.glbt1.gdg/admin/mw/SAMobileWebService.php/GetCompleteE" +
            "rrorCodeList", RequestNamespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb", ResponseNamespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public mwErrorCodeList[] GetCompleteErrorCodeList(string clientid) {
            object[] results = this.Invoke("GetCompleteErrorCodeList", new object[] {
                        clientid});
            return ((mwErrorCodeList[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompleteErrorCodeListAsync(string clientid) {
            this.GetCompleteErrorCodeListAsync(clientid, null);
        }
        
        /// <remarks/>
        public void GetCompleteErrorCodeListAsync(string clientid, object userState) {
            if ((this.GetCompleteErrorCodeListOperationCompleted == null)) {
                this.GetCompleteErrorCodeListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompleteErrorCodeListOperationCompleted);
            }
            this.InvokeAsync("GetCompleteErrorCodeList", new object[] {
                        clientid}, this.GetCompleteErrorCodeListOperationCompleted, userState);
        }
        
        private void OnGetCompleteErrorCodeListOperationCompleted(object arg) {
            if ((this.GetCompleteErrorCodeListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompleteErrorCodeListCompleted(this, new GetCompleteErrorCodeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
    public partial class mwDomainReturnStruct {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        private string domainCountField;
        
        private mwDomainStruct[] domainListField;
        
        /// <remarks/>
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public string domainCount {
            get {
                return this.domainCountField;
            }
            set {
                this.domainCountField = value;
            }
        }
        
        /// <remarks/>
        public mwDomainStruct[] domainList {
            get {
                return this.domainListField;
            }
            set {
                this.domainListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
    public partial class mwDomainStruct {
        
        private string domainField;
        
        /// <remarks/>
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
    public partial class mwErrorCodeList {
        
        private ushort returnCodeField;
        
        private string returnTextField;
        
        /// <remarks/>
        public ushort returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string returnText {
            get {
                return this.returnTextField;
            }
            set {
                this.returnTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
    public partial class mwTrafficSourcesStruct {
        
        private string sourceField;
        
        private string visitsField;
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Visits {
            get {
                return this.visitsField;
            }
            set {
                this.visitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
    public partial class mwTrafficSourcesReturnStruct {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        private string shopperField;
        
        private mwTrafficSourcesStruct[] trafficSourcesField;
        
        /// <remarks/>
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public string shopper {
            get {
                return this.shopperField;
            }
            set {
                this.shopperField = value;
            }
        }
        
        /// <remarks/>
        public mwTrafficSourcesStruct[] trafficSources {
            get {
                return this.trafficSourcesField;
            }
            set {
                this.trafficSourcesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
    public partial class mwMostPopDayStruct {
        
        private string dayField;
        
        private string pageViewsField;
        
        /// <remarks/>
        public string Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string PageViews {
            get {
                return this.pageViewsField;
            }
            set {
                this.pageViewsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
    public partial class mwMostPopDayReturnStruct {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        private string shopperField;
        
        private mwMostPopDayStruct[] mostPopDayStatsField;
        
        /// <remarks/>
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public string shopper {
            get {
                return this.shopperField;
            }
            set {
                this.shopperField = value;
            }
        }
        
        /// <remarks/>
        public mwMostPopDayStruct[] mostPopDayStats {
            get {
                return this.mostPopDayStatsField;
            }
            set {
                this.mostPopDayStatsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
    public partial class mwUSVisitorStruct {
        
        private string stateField;
        
        private string visitorsField;
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Visitors {
            get {
                return this.visitorsField;
            }
            set {
                this.visitorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
    public partial class mwUSVisReturnStruct {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        private string shopperField;
        
        private mwUSVisitorStruct[] usVisitorStatsField;
        
        /// <remarks/>
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public string shopper {
            get {
                return this.shopperField;
            }
            set {
                this.shopperField = value;
            }
        }
        
        /// <remarks/>
        public mwUSVisitorStruct[] usVisitorStats {
            get {
                return this.usVisitorStatsField;
            }
            set {
                this.usVisitorStatsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
    public partial class mwVisitorStruct {
        
        private string statsDateField;
        
        private string uniqueVisitorsField;
        
        private string visitorsField;
        
        /// <remarks/>
        public string StatsDate {
            get {
                return this.statsDateField;
            }
            set {
                this.statsDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string UniqueVisitors {
            get {
                return this.uniqueVisitorsField;
            }
            set {
                this.uniqueVisitorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string Visitors {
            get {
                return this.visitorsField;
            }
            set {
                this.visitorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.godaddy.com/SiteAnalytics/mw/SAMobileWeb")]
    public partial class mwVisReturnStruct {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        private string shopperField;
        
        private mwVisitorStruct[] visitorStatsField;
        
        /// <remarks/>
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        public string shopper {
            get {
                return this.shopperField;
            }
            set {
                this.shopperField = value;
            }
        }
        
        /// <remarks/>
        public mwVisitorStruct[] visitorStats {
            get {
                return this.visitorStatsField;
            }
            set {
                this.visitorStatsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDomainListByShopperCompletedEventHandler(object sender, GetDomainListByShopperCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDomainListByShopperCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDomainListByShopperCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mwDomainReturnStruct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mwDomainReturnStruct)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VisitorsCompletedEventHandler(object sender, VisitorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VisitorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VisitorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mwVisReturnStruct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mwVisReturnStruct)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void USVisByLocationCompletedEventHandler(object sender, USVisByLocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class USVisByLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal USVisByLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mwUSVisReturnStruct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mwUSVisReturnStruct)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MostPopularDayCompletedEventHandler(object sender, MostPopularDayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostPopularDayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostPopularDayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mwMostPopDayReturnStruct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mwMostPopDayReturnStruct)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TrafficSourcesCompletedEventHandler(object sender, TrafficSourcesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrafficSourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrafficSourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mwTrafficSourcesReturnStruct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mwTrafficSourcesReturnStruct)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCompleteErrorCodeListCompletedEventHandler(object sender, GetCompleteErrorCodeListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompleteErrorCodeListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompleteErrorCodeListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mwErrorCodeList[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mwErrorCodeList[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591