//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace Atlantis.Framework.QSCSetupAccount.Impl.QSCService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FOSServiceSoapBinding", Namespace="http://ws.fastshoppingcart.com/xfws/accountSetup")]
    public partial class FOSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getThemeInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback setupAccountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FOSService() {
            this.Url = global::Atlantis.Framework.QSCSetupAccount.Impl.Properties.Settings.Default.Atlantis_Framework_QSCSetupAccount_Impl_QSCService_FOSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getThemeInformationCompletedEventHandler getThemeInformationCompleted;
        
        /// <remarks/>
        public event setupAccountCompletedEventHandler setupAccountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.fastshoppingcart.com/xfws/accountSetup", ResponseNamespace="http://ws.fastshoppingcart.com/xfws/accountSetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("themeInformation")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public template[] getThemeInformation() {
            object[] results = this.Invoke("getThemeInformation", new object[0]);
            return ((template[])(results[0]));
        }
        
        /// <remarks/>
        public void getThemeInformationAsync() {
            this.getThemeInformationAsync(null);
        }
        
        /// <remarks/>
        public void getThemeInformationAsync(object userState) {
            if ((this.getThemeInformationOperationCompleted == null)) {
                this.getThemeInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetThemeInformationOperationCompleted);
            }
            this.InvokeAsync("getThemeInformation", new object[0], this.getThemeInformationOperationCompleted, userState);
        }
        
        private void OngetThemeInformationOperationCompleted(object arg) {
            if ((this.getThemeInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getThemeInformationCompleted(this, new getThemeInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.fastshoppingcart.com/xfws/accountSetup", ResponseNamespace="http://ws.fastshoppingcart.com/xfws/accountSetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("acountSetup")]
        public acountSetup setupAccount([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string orionGUID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string domainName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emailAddress, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string companyName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string themeID) {
            object[] results = this.Invoke("setupAccount", new object[] {
                        orionGUID,
                        domainName,
                        emailAddress,
                        companyName,
                        themeID});
            return ((acountSetup)(results[0]));
        }
        
        /// <remarks/>
        public void setupAccountAsync(string orionGUID, string domainName, string emailAddress, string companyName, string themeID) {
            this.setupAccountAsync(orionGUID, domainName, emailAddress, companyName, themeID, null);
        }
        
        /// <remarks/>
        public void setupAccountAsync(string orionGUID, string domainName, string emailAddress, string companyName, string themeID, object userState) {
            if ((this.setupAccountOperationCompleted == null)) {
                this.setupAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetupAccountOperationCompleted);
            }
            this.InvokeAsync("setupAccount", new object[] {
                        orionGUID,
                        domainName,
                        emailAddress,
                        companyName,
                        themeID}, this.setupAccountOperationCompleted, userState);
        }
        
        private void OnsetupAccountOperationCompleted(object arg) {
            if ((this.setupAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setupAccountCompleted(this, new setupAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.fastshoppingcart.com/xfws/accountSetup")]
    public partial class template {
        
        private string backgroundIDField;
        
        private string srcField;
        
        private string thumbnailSrcField;
        
        /// <remarks/>
        public string backgroundID {
            get {
                return this.backgroundIDField;
            }
            set {
                this.backgroundIDField = value;
            }
        }
        
        /// <remarks/>
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        public string thumbnailSrc {
            get {
                return this.thumbnailSrcField;
            }
            set {
                this.thumbnailSrcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.fastshoppingcart.com/xfws/accountSetup")]
    public partial class acountSetup {
        
        private int responseCodeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string responseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getThemeInformationCompletedEventHandler(object sender, getThemeInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getThemeInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getThemeInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public template[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((template[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void setupAccountCompletedEventHandler(object sender, setupAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setupAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setupAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public acountSetup Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((acountSetup)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591