repos:
  -   repo: https://github.com/godaddy/tartufo
      rev: v3.3.1
      hooks:
        - id: tartufo
          name: tartufo
          entry: tartufo
          args: [pre-commit]
          language: python
          pass_filenames: false
