//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using Atlantis.Framework.Entity.Interface;
using Atlantis.Framework.Entity.Interface.SelfTracking;

namespace Atlantis.Framework.CampaignManagerData.Interface.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Campaign))]
    [KnownType(typeof(Company))]
    public partial class CampaignCompanyMap:  IAtlantisEntity, IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int CampaignCompanyMapID
        {
            get { return _campaignCompanyMapID; }
            set
            {
                if (_campaignCompanyMapID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CampaignCompanyMapID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _campaignCompanyMapID = value;
                    OnPropertyChanged("CampaignCompanyMapID");
                }
            }
        }
        private int _campaignCompanyMapID;
    
        [DataMember]
        public int CampaignID
        {
            get { return _campaignID; }
            set
            {
                if (_campaignID != value)
                {
                    ChangeTracker.RecordOriginalValue("CampaignID", _campaignID);
                    if (!IsDeserializing)
                    {
                        if (Campaign != null && Campaign.CampaignID != value)
                        {
                            Campaign = null;
                        }
                    }
                    _campaignID = value;
                    OnPropertyChanged("CampaignID");
                }
            }
        }
        private int _campaignID;
    
        [DataMember]
        public int CompanyID
        {
            get { return _companyID; }
            set
            {
                if (_companyID != value)
                {
                    ChangeTracker.RecordOriginalValue("CompanyID", _companyID);
                    if (!IsDeserializing)
                    {
                        if (Company != null && Company.CompanyID != value)
                        {
                            Company = null;
                        }
                    }
                    _companyID = value;
                    OnPropertyChanged("CompanyID");
                }
            }
        }
        private int _companyID;
    
        [DataMember]
        public System.DateTime DateAdded
        {
            get { return _dateAdded; }
            set
            {
                if (_dateAdded != value)
                {
                    _dateAdded = value;
                    OnPropertyChanged("DateAdded");
                }
            }
        }
        private System.DateTime _dateAdded;
    
        [DataMember]
        public System.DateTime DateUpdated
        {
            get { return _dateUpdated; }
            set
            {
                if (_dateUpdated != value)
                {
                    _dateUpdated = value;
                    OnPropertyChanged("DateUpdated");
                }
            }
        }
        private System.DateTime _dateUpdated;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Campaign Campaign
        {
            get { return _campaign; }
            set
            {
                if (!ReferenceEquals(_campaign, value))
                {
                    var previousValue = _campaign;
                    _campaign = value;
                    FixupCampaign(previousValue);
                    OnNavigationPropertyChanged("Campaign");
                }
            }
        }
        private Campaign _campaign;
    
        [DataMember]
        public Company Company
        {
            get { return _company; }
            set
            {
                if (!ReferenceEquals(_company, value))
                {
                    var previousValue = _company;
                    _company = value;
                    FixupCompany(previousValue);
                    OnNavigationPropertyChanged("Company");
                }
            }
        }
        private Company _company;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Campaign = null;
            Company = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupCampaign(Campaign previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.CampaignCompanyMaps.Contains(this))
            {
                previousValue.CampaignCompanyMaps.Remove(this);
            }
    
            if (Campaign != null)
            {
                if (!Campaign.CampaignCompanyMaps.Contains(this))
                {
                    Campaign.CampaignCompanyMaps.Add(this);
                }
    
                CampaignID = Campaign.CampaignID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Campaign")
                    && (ChangeTracker.OriginalValues["Campaign"] == Campaign))
                {
                    ChangeTracker.OriginalValues.Remove("Campaign");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Campaign", previousValue);
                }
                if (Campaign != null && !Campaign.ChangeTracker.ChangeTrackingEnabled)
                {
                    Campaign.StartTracking();
                }
            }
        }
    
        private void FixupCompany(Company previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.CampaignCompanyMaps.Contains(this))
            {
                previousValue.CampaignCompanyMaps.Remove(this);
            }
    
            if (Company != null)
            {
                if (!Company.CampaignCompanyMaps.Contains(this))
                {
                    Company.CampaignCompanyMaps.Add(this);
                }
    
                CompanyID = Company.CompanyID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Company")
                    && (ChangeTracker.OriginalValues["Company"] == Company))
                {
                    ChangeTracker.OriginalValues.Remove("Company");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Company", previousValue);
                }
                if (Company != null && !Company.ChangeTracker.ChangeTrackingEnabled)
                {
                    Company.StartTracking();
                }
            }
        }

        #endregion
    }
}
