//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using Atlantis.Framework.Entity.Interface;
using Atlantis.Framework.Entity.Interface.SelfTracking;

namespace Atlantis.Framework.CampaignManagerData.Interface.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RuleBlock))]
    [KnownType(typeof(Segment))]
    public partial class SegmentRuleBlockMap:  IAtlantisEntity, IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int SegmentRuleBlockMapID
        {
            get { return _segmentRuleBlockMapID; }
            set
            {
                if (_segmentRuleBlockMapID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'SegmentRuleBlockMapID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _segmentRuleBlockMapID = value;
                    OnPropertyChanged("SegmentRuleBlockMapID");
                }
            }
        }
        private int _segmentRuleBlockMapID;
    
        [DataMember]
        public int SegmentID
        {
            get { return _segmentID; }
            set
            {
                if (_segmentID != value)
                {
                    ChangeTracker.RecordOriginalValue("SegmentID", _segmentID);
                    if (!IsDeserializing)
                    {
                        if (Segment != null && Segment.SegmentID != value)
                        {
                            Segment = null;
                        }
                    }
                    _segmentID = value;
                    OnPropertyChanged("SegmentID");
                }
            }
        }
        private int _segmentID;
    
        [DataMember]
        public int RuleBlockID
        {
            get { return _ruleBlockID; }
            set
            {
                if (_ruleBlockID != value)
                {
                    ChangeTracker.RecordOriginalValue("RuleBlockID", _ruleBlockID);
                    if (!IsDeserializing)
                    {
                        if (RuleBlock != null && RuleBlock.RuleBlockID != value)
                        {
                            RuleBlock = null;
                        }
                    }
                    _ruleBlockID = value;
                    OnPropertyChanged("RuleBlockID");
                }
            }
        }
        private int _ruleBlockID;
    
        [DataMember]
        public System.DateTime DateAdded
        {
            get { return _dateAdded; }
            set
            {
                if (_dateAdded != value)
                {
                    _dateAdded = value;
                    OnPropertyChanged("DateAdded");
                }
            }
        }
        private System.DateTime _dateAdded;
    
        [DataMember]
        public System.DateTime DateUpdated
        {
            get { return _dateUpdated; }
            set
            {
                if (_dateUpdated != value)
                {
                    _dateUpdated = value;
                    OnPropertyChanged("DateUpdated");
                }
            }
        }
        private System.DateTime _dateUpdated;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public RuleBlock RuleBlock
        {
            get { return _ruleBlock; }
            set
            {
                if (!ReferenceEquals(_ruleBlock, value))
                {
                    var previousValue = _ruleBlock;
                    _ruleBlock = value;
                    FixupRuleBlock(previousValue);
                    OnNavigationPropertyChanged("RuleBlock");
                }
            }
        }
        private RuleBlock _ruleBlock;
    
        [DataMember]
        public Segment Segment
        {
            get { return _segment; }
            set
            {
                if (!ReferenceEquals(_segment, value))
                {
                    var previousValue = _segment;
                    _segment = value;
                    FixupSegment(previousValue);
                    OnNavigationPropertyChanged("Segment");
                }
            }
        }
        private Segment _segment;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            RuleBlock = null;
            Segment = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupRuleBlock(RuleBlock previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.SegmentRuleBlockMaps.Contains(this))
            {
                previousValue.SegmentRuleBlockMaps.Remove(this);
            }
    
            if (RuleBlock != null)
            {
                if (!RuleBlock.SegmentRuleBlockMaps.Contains(this))
                {
                    RuleBlock.SegmentRuleBlockMaps.Add(this);
                }
    
                RuleBlockID = RuleBlock.RuleBlockID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("RuleBlock")
                    && (ChangeTracker.OriginalValues["RuleBlock"] == RuleBlock))
                {
                    ChangeTracker.OriginalValues.Remove("RuleBlock");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("RuleBlock", previousValue);
                }
                if (RuleBlock != null && !RuleBlock.ChangeTracker.ChangeTrackingEnabled)
                {
                    RuleBlock.StartTracking();
                }
            }
        }
    
        private void FixupSegment(Segment previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.SegmentRuleBlockMaps.Contains(this))
            {
                previousValue.SegmentRuleBlockMaps.Remove(this);
            }
    
            if (Segment != null)
            {
                if (!Segment.SegmentRuleBlockMaps.Contains(this))
                {
                    Segment.SegmentRuleBlockMaps.Add(this);
                }
    
                SegmentID = Segment.SegmentID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Segment")
                    && (ChangeTracker.OriginalValues["Segment"] == Segment))
                {
                    ChangeTracker.OriginalValues.Remove("Segment");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Segment", previousValue);
                }
                if (Segment != null && !Segment.ChangeTracker.ChangeTrackingEnabled)
                {
                    Segment.StartTracking();
                }
            }
        }

        #endregion
    }
}
