//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlantis.Framework.TrafficSmsTracking.Impl.FbiSmsTrackingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FbiSmsTrackingService.IfbiSmsTrackingService")]
    public interface IfbiSmsTrackingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IfbiSmsTrackingService/SendData", ReplyAction="http://tempuri.org/IfbiSmsTrackingService/SendDataResponse")]
        void SendData(System.Guid smsID, System.Guid air2WebID, string phoneNumberHash, string mobileCarrier, System.DateTime inboundTime, string inboundMessage, string searchedSld, string searchedTld, bool isAvailable, System.DateTime outboundTime, string outboundMessage, string actionPerformed, string sentSld, string sentTld, string mobileServer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IfbiSmsTrackingServiceChannel : Atlantis.Framework.TrafficSmsTracking.Impl.FbiSmsTrackingService.IfbiSmsTrackingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IfbiSmsTrackingServiceClient : System.ServiceModel.ClientBase<Atlantis.Framework.TrafficSmsTracking.Impl.FbiSmsTrackingService.IfbiSmsTrackingService>, Atlantis.Framework.TrafficSmsTracking.Impl.FbiSmsTrackingService.IfbiSmsTrackingService {
        
        public IfbiSmsTrackingServiceClient() {
        }
        
        public IfbiSmsTrackingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IfbiSmsTrackingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IfbiSmsTrackingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IfbiSmsTrackingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendData(System.Guid smsID, System.Guid air2WebID, string phoneNumberHash, string mobileCarrier, System.DateTime inboundTime, string inboundMessage, string searchedSld, string searchedTld, bool isAvailable, System.DateTime outboundTime, string outboundMessage, string actionPerformed, string sentSld, string sentTld, string mobileServer) {
            base.Channel.SendData(smsID, air2WebID, phoneNumberHash, mobileCarrier, inboundTime, inboundMessage, searchedSld, searchedTld, isAvailable, outboundTime, outboundMessage, actionPerformed, sentSld, sentTld, mobileServer);
        }
    }
}
