//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Atlantis.Framework.FastballGetOffersMsgData.Impl.OffersAPIWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="#fastball.offersapi")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOffersAndMessageDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOffersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOfferByOfferIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductsByProductGroupOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Atlantis.Framework.FastballGetOffersMsgData.Impl.Properties.Settings.Default.Atlantis_Framework_FastballGetOffersMsgData_Impl_OffersAPIWS_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOffersAndMessageDataCompletedEventHandler GetOffersAndMessageDataCompleted;
        
        /// <remarks/>
        public event GetOffersCompletedEventHandler GetOffersCompleted;
        
        /// <remarks/>
        public event GetOfferByOfferIDCompletedEventHandler GetOfferByOfferIDCompleted;
        
        /// <remarks/>
        public event GetProductsByProductGroupCompletedEventHandler GetProductsByProductGroupCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#fastball.offersapi/GetOffersAndMessageData", RequestNamespace="#fastball.offersapi", ResponseNamespace="#fastball.offersapi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("OfferResult", IsNullable=true)]
        public OfferResult GetOffersAndMessageData(string ChannelRequestXml, string CandidateRequestXml) {
            object[] results = this.Invoke("GetOffersAndMessageData", new object[] {
                        ChannelRequestXml,
                        CandidateRequestXml});
            return ((OfferResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetOffersAndMessageDataAsync(string ChannelRequestXml, string CandidateRequestXml) {
            this.GetOffersAndMessageDataAsync(ChannelRequestXml, CandidateRequestXml, null);
        }
        
        /// <remarks/>
        public void GetOffersAndMessageDataAsync(string ChannelRequestXml, string CandidateRequestXml, object userState) {
            if ((this.GetOffersAndMessageDataOperationCompleted == null)) {
                this.GetOffersAndMessageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOffersAndMessageDataOperationCompleted);
            }
            this.InvokeAsync("GetOffersAndMessageData", new object[] {
                        ChannelRequestXml,
                        CandidateRequestXml}, this.GetOffersAndMessageDataOperationCompleted, userState);
        }
        
        private void OnGetOffersAndMessageDataOperationCompleted(object arg) {
            if ((this.GetOffersAndMessageDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOffersAndMessageDataCompleted(this, new GetOffersAndMessageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#fastball.offersapi/GetOffers", RequestNamespace="#fastball.offersapi", ResponseNamespace="#fastball.offersapi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("OfferResultXml")]
        public string GetOffers(string ChannelRequestXml, string CandidateRequestXml) {
            object[] results = this.Invoke("GetOffers", new object[] {
                        ChannelRequestXml,
                        CandidateRequestXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOffersAsync(string ChannelRequestXml, string CandidateRequestXml) {
            this.GetOffersAsync(ChannelRequestXml, CandidateRequestXml, null);
        }
        
        /// <remarks/>
        public void GetOffersAsync(string ChannelRequestXml, string CandidateRequestXml, object userState) {
            if ((this.GetOffersOperationCompleted == null)) {
                this.GetOffersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOffersOperationCompleted);
            }
            this.InvokeAsync("GetOffers", new object[] {
                        ChannelRequestXml,
                        CandidateRequestXml}, this.GetOffersOperationCompleted, userState);
        }
        
        private void OnGetOffersOperationCompleted(object arg) {
            if ((this.GetOffersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOffersCompleted(this, new GetOffersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#fastball.offersapi/GetOfferByOfferID", RequestNamespace="#fastball.offersapi", ResponseNamespace="#fastball.offersapi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResultCode")]
        public int GetOfferByOfferID(string OfferID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out Offer Offer) {
            object[] results = this.Invoke("GetOfferByOfferID", new object[] {
                        OfferID});
            Offer = ((Offer)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetOfferByOfferIDAsync(string OfferID) {
            this.GetOfferByOfferIDAsync(OfferID, null);
        }
        
        /// <remarks/>
        public void GetOfferByOfferIDAsync(string OfferID, object userState) {
            if ((this.GetOfferByOfferIDOperationCompleted == null)) {
                this.GetOfferByOfferIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOfferByOfferIDOperationCompleted);
            }
            this.InvokeAsync("GetOfferByOfferID", new object[] {
                        OfferID}, this.GetOfferByOfferIDOperationCompleted, userState);
        }
        
        private void OnGetOfferByOfferIDOperationCompleted(object arg) {
            if ((this.GetOfferByOfferIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOfferByOfferIDCompleted(this, new GetOfferByOfferIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#fastball.offersapi/GetProductsByProductGroup", RequestNamespace="#fastball.offersapi", ResponseNamespace="#fastball.offersapi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResultCode")]
        public int GetProductsByProductGroup(string ProductGroup, out Product[] ProductList) {
            object[] results = this.Invoke("GetProductsByProductGroup", new object[] {
                        ProductGroup});
            ProductList = ((Product[])(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductsByProductGroupAsync(string ProductGroup) {
            this.GetProductsByProductGroupAsync(ProductGroup, null);
        }
        
        /// <remarks/>
        public void GetProductsByProductGroupAsync(string ProductGroup, object userState) {
            if ((this.GetProductsByProductGroupOperationCompleted == null)) {
                this.GetProductsByProductGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsByProductGroupOperationCompleted);
            }
            this.InvokeAsync("GetProductsByProductGroup", new object[] {
                        ProductGroup}, this.GetProductsByProductGroupOperationCompleted, userState);
        }
        
        private void OnGetProductsByProductGroupOperationCompleted(object arg) {
            if ((this.GetProductsByProductGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductsByProductGroupCompleted(this, new GetProductsByProductGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="#fastball.offersapi")]
    public partial class OfferResult {
        
        private int resultCodeField;
        
        private string candidateAttributeXmlField;
        
        private Offer[] selectedOffersField;
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CandidateAttributeXml {
            get {
                return this.candidateAttributeXmlField;
            }
            set {
                this.candidateAttributeXmlField = value;
            }
        }
        
        /// <remarks/>
        public Offer[] SelectedOffers {
            get {
                return this.selectedOffersField;
            }
            set {
                this.selectedOffersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="#fastball.offersapi")]
    public partial class Offer {
        
        private OfferMessageData messageDataField;
        
        private string fbiOfferIDField;
        
        private string discountTypeField;
        
        private string fastballDiscountField;
        
        private string fastballOrderDiscountField;
        
        private string productGroupCodeField;
        
        /// <remarks/>
        public OfferMessageData MessageData {
            get {
                return this.messageDataField;
            }
            set {
                this.messageDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fbiOfferID {
            get {
                return this.fbiOfferIDField;
            }
            set {
                this.fbiOfferIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string discountType {
            get {
                return this.discountTypeField;
            }
            set {
                this.discountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fastballDiscount {
            get {
                return this.fastballDiscountField;
            }
            set {
                this.fastballDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fastballOrderDiscount {
            get {
                return this.fastballOrderDiscountField;
            }
            set {
                this.fastballOrderDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string productGroupCode {
            get {
                return this.productGroupCodeField;
            }
            set {
                this.productGroupCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="#fastball.offersapi")]
    public partial class OfferMessageData {
        
        private OfferMessageDataItem[] dataItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DataItem")]
        public OfferMessageDataItem[] DataItems {
            get {
                return this.dataItemsField;
            }
            set {
                this.dataItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="#fastball.offersapi")]
    public partial class OfferMessageDataItem {
        
        private OfferMessageDataItemAttribute[] attributesField;
        
        private string idField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attribute")]
        public OfferMessageDataItemAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="#fastball.offersapi")]
    public partial class OfferMessageDataItemAttribute {
        
        private string[] valuesField;
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Value")]
        public string[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="#fastball.offersapi")]
    public partial class Product {
        
        private int unifiedProductIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int UnifiedProductID {
            get {
                return this.unifiedProductIDField;
            }
            set {
                this.unifiedProductIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOffersAndMessageDataCompletedEventHandler(object sender, GetOffersAndMessageDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOffersAndMessageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOffersAndMessageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OfferResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OfferResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOffersCompletedEventHandler(object sender, GetOffersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOffersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOffersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOfferByOfferIDCompletedEventHandler(object sender, GetOfferByOfferIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOfferByOfferIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOfferByOfferIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Offer Offer {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Offer)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetProductsByProductGroupCompletedEventHandler(object sender, GetProductsByProductGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductsByProductGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductsByProductGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Product[] ProductList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product[])(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591