//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlantis.Framework.TrafficPageEvent.Impl.Traffic {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Traffic.IPageEventService")]
    public interface IPageEventService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPageEventService/LogPageEvents", ReplyAction="http://tempuri.org/IPageEventService/LogPageEventsResponse")]
        void LogPageEvents(string pathway, string pageName, int cicode, string eventType, string ciimpressions, string userKeyValuePairs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPageEventServiceChannel : Atlantis.Framework.TrafficPageEvent.Impl.Traffic.IPageEventService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PageEventServiceClient : System.ServiceModel.ClientBase<Atlantis.Framework.TrafficPageEvent.Impl.Traffic.IPageEventService>, Atlantis.Framework.TrafficPageEvent.Impl.Traffic.IPageEventService {
        
        public PageEventServiceClient() {
        }
        
        public PageEventServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PageEventServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PageEventServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PageEventServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LogPageEvents(string pathway, string pageName, int cicode, string eventType, string ciimpressions, string userKeyValuePairs) {
            base.Channel.LogPageEvents(pathway, pageName, cicode, eventType, ciimpressions, userKeyValuePairs);
        }
    }
}
