//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Atlantis.Framework.MYAWstQuoteStatusByErid.Impl.QuoteWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MYAServiceSoap", Namespace="http://GoDaddy.Quote.WebService")]
    public partial class MYAService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HealthCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusByAccountIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MYAService() {
            this.Url = global::Atlantis.Framework.MYAWstQuoteStatusByErid.Impl.Properties.Settings.Default.Atlantis_Framework_MYAWstQuoteStatusByErid_Impl_QuoteWebService_MYAService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HealthCheckCompletedEventHandler HealthCheckCompleted;
        
        /// <remarks/>
        public event GetStatusByAccountIdCompletedEventHandler GetStatusByAccountIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GoDaddy.Quote.WebService/HealthCheck", RequestNamespace="http://GoDaddy.Quote.WebService", ResponseNamespace="http://GoDaddy.Quote.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HealthCheck() {
            object[] results = this.Invoke("HealthCheck", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HealthCheckAsync() {
            this.HealthCheckAsync(null);
        }
        
        /// <remarks/>
        public void HealthCheckAsync(object userState) {
            if ((this.HealthCheckOperationCompleted == null)) {
                this.HealthCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHealthCheckOperationCompleted);
            }
            this.InvokeAsync("HealthCheck", new object[0], this.HealthCheckOperationCompleted, userState);
        }
        
        private void OnHealthCheckOperationCompleted(object arg) {
            if ((this.HealthCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HealthCheckCompleted(this, new HealthCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GoDaddy.Quote.WebService/GetStatusByAccountId", RequestNamespace="http://GoDaddy.Quote.WebService", ResponseNamespace="http://GoDaddy.Quote.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStatusByAccountId(string accountId) {
            object[] results = this.Invoke("GetStatusByAccountId", new object[] {
                        accountId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusByAccountIdAsync(string accountId) {
            this.GetStatusByAccountIdAsync(accountId, null);
        }
        
        /// <remarks/>
        public void GetStatusByAccountIdAsync(string accountId, object userState) {
            if ((this.GetStatusByAccountIdOperationCompleted == null)) {
                this.GetStatusByAccountIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusByAccountIdOperationCompleted);
            }
            this.InvokeAsync("GetStatusByAccountId", new object[] {
                        accountId}, this.GetStatusByAccountIdOperationCompleted, userState);
        }
        
        private void OnGetStatusByAccountIdOperationCompleted(object arg) {
            if ((this.GetStatusByAccountIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusByAccountIdCompleted(this, new GetStatusByAccountIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HealthCheckCompletedEventHandler(object sender, HealthCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HealthCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HealthCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetStatusByAccountIdCompletedEventHandler(object sender, GetStatusByAccountIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusByAccountIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusByAccountIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591